name: build-iam-auth

on:
  workflow_dispatch:
  schedule:
   - cron: "0 10 * * *"

env:
  GIT_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
  GIT_USERNAME: github-actions[bot]
  BRANCH_NAME: update-lambda
  GITHUB_TOKEN: ${{ secrets.ACTION_TOKEN }}
  REPO_NAME: champ-oss/terraform-aws-mysql
  FILE_NAME: package.zip

defaults:
  run:
    shell: bash
    working-directory: iam_auth

jobs:
  build-iam-auth:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          architecture: 'x64'

      - name: check out branch
        run: |
          git config --global user.email "$GIT_EMAIL" && git config --global user.name "$GIT_USERNAME"
          git fetch && git checkout -b "$BRANCH_NAME" origin/"$BRANCH_NAME" || git checkout -b "$BRANCH_NAME"
          git reset --hard origin/$BRANCH_NAME

      - name: build
        run: pip install -r requirements.txt -t .

      - name: zip
        run: zip -r $FILE_NAME *

      - name: git commit
        run: |
          git add $FILE_NAME
          git commit -m "update lambda $FILE_NAME"

      - name: git push
        run: git push https://x-access-token:${GITHUB_TOKEN}@github.com/${REPO_NAME}.git

      - name: create pull request
        run: |
          jq -n --arg title "update lambda $FILE_NAME" --arg head "$BRANCH_NAME" --arg base main '{title:$title,head:$head,base:$base}' | curl -d @- \
              -X POST \
              -H "Accept: application/vnd.github.v3+json" \
              -u ${USERNAME}:${GITHUB_TOKEN} \
              --silent \
              ${GITHUB_API_URL}/repos/${REPO_NAME}/pulls
