on:
  workflow_dispatch:
  push:

env:
  REPO: champtitles/terraform-aws-mysql-iam-auth
  SHA: ${{ github.sha }}
  DOCKER_USERNAME: champtitles
  DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_TOKEN }}

jobs:
  build-iam-auth:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2.0.0
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3.0.0
        with:
          context: iam_auth
          push: true
          tags: |
            ${{ env.REPO }}:${{ env.SHA }}